# https://pre-commit.com/
ci:
    autofix_prs: false
exclude: docs/_static
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.5
    hooks:
      - id: shellcheck
        files: scripts/[^/]*$
        types: []

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        files: scripts\/python\/(([^.]+)$|.*\.py)

  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
        files: scripts\/python\/(([^.]+)$|.*\.py)

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
       - id: flake8
         files: scripts\/python\/(([^.]+)$|.*\.py)
         args: [--max-line-length=88]
