#!/bin/bash
./setup -d nemo -x
./setup -d head -c HEAD -x

cd nemo || exit
COMMIT=$(git rev-parse HEAD)
cd ../head || exit
COMMIT_HEAD=$(git rev-parse HEAD)
cd .. || exit

if [[ "$COMMIT" == "$COMMIT_HEAD" ]]; then
    exit
fi

cat << EOF > "ISSUE.md"
---
title: Comparison commit ${COMMIT_HEAD::8} and ${COMMIT::8}
---
Hi there,
commit [${COMMIT_HEAD::8}](https://forge.nemo-ocean.eu/nemo/core/-/commit/$COMMIT_HEAD) has been pushed.
EOF

WARNED=0
# Check F90
for DIR in "./ext" "./cfgs" "./tools"; do
    for FILE in $(find "$DIR" -name "*.F90"); do
        BASENAME=$(basename "$FILE")
        FILEA=$(find nemo -name "$BASENAME")
        FILEB=$(find head -name "$BASENAME")
        DIFF=$(diff "$FILEA" "$FILEB")
        if [ "$DIFF" != "" ]; then
            WARNED=1
            cat << EOF >> "ISSUE.md"

⚠️WARNING⚠️
[$BASENAME](https://github.com/immerse-project/wp6.2-demonstrator/blob/main/$FILE) needs to be updated:
\`\`\`diff
diff $FILEA $FILEB
$DIFF
\`\`\`
EOF
        fi
    done
done

# Check namelists
for DIR in "tools/DOMAINcfg" "cfgs/SHARED"; do
    for FILEA in $(find ./nemo/$DIR ! -path ./nemo/$DIR -prune -type f -name "namelist_ref" -o -name "namelist_ice_ref"); do
        FILEB=${FILEA/nemo/head}
        DIFF=$(diff "$FILEA" "$FILEB")
        if [ "$DIFF" != "" ]; then
            WARNED=1
            cat << EOF >> "ISSUE.md"

⚠️WARNING⚠️
\`${FILEA/.\/nemo\//}\` has changed:
\`\`\`diff
diff $FILEA $FILEB
$DIFF
\`\`\`
EOF
        fi
    done
done

# Bye-Bye
if [[ "$WARNED" == 0 ]]; then
    cat << EOF >> "ISSUE.md"

🚀THERE ARE NO CONFLICTS🚀
Consider setting \`COMMIT=$COMMIT_HEAD\` [here](https://github.com/immerse-project/wp6.2-demonstrator/blob/main/scripts/setup#L5).
EOF
fi

