#!/bin/bash

WD=$PWD
NEMODIR="./nemo/dev_agrif_immerse"

for DIR in {./tools/DOMAINcfg/*/,./cfgs/*/*/}; do

    cd "${DIR//./$NEMODIR}" || exit

    # Create concise and combine namelist
    for NAMCFG in ./*namelist*_cfg; do
        NAMREF=${NAMCFG//_cfg/_ref}
        NAMCOM=${NAMCFG//_cfg/}
        "$WD"/scripts/python/print_concise_namelist_cfg -c "$NAMCFG" -r "$NAMREF" --overwrite
        "$WD"/scripts/python/combine_namelists -c "$NAMCFG" -r "$NAMREF" -o "$NAMCOM"
        cp {"$NAMCFG","$NAMCOM"} "$WD"/"$DIR"
    done

    cd "$WD" || exit
done

