name: Check latest commit

on:
  push:
    branches:
      - "main"
  schedule:
    - cron: "0 * * * *"

permissions:
  contents: read
  issues: write 

jobs:
  open_issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check latest commit
        shell: bash -l {0}
        run: ./scripts/check_latest_commit

      - name: Check ISSUE.md existence
        id: check_ISSUE
        uses: andstor/file-existence-action@v1
        with:
          files: "ISSUE.md"

      - name: Open an issue
        if: steps.check_ISSUE.outputs.files_exists == 'true'
        uses: dblock/create-a-github-issue@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: ISSUE.md
          assignees: malmans2, atb299, jdha
          update_existing: true
          search_existing: all
